# Generated by Django 5.0.7 on 2024-08-16 10:22

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('users', '0005_alter_order_user'),
    ]

    operations = [
        migrations.AddField(
            model_name='order',
            name='contact_no',
            field=models.CharField(max_length=13, null=True),
        ),
    ]
