# Generated by Django 5.0.7 on 2024-08-23 08:20

from django.conf import settings
from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('users', '0009_alter_payment_order'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='payment',
            options={},
        ),
        migrations.AlterUniqueTogether(
            name='payment',
            unique_together={('user', 'order')},
        ),
    ]
