# Generated by Django 5.0.7 on 2024-08-23 10:13

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('users', '0010_alter_payment_options_alter_payment_unique_together'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='payment',
            options={'get_latest_by': 'created'},
        ),
        migrations.AlterUniqueTogether(
            name='payment',
            unique_together=set(),
        ),
    ]
