# Generated by Django 5.0.7 on 2024-08-29 11:22

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('users', '0013_order_status'),
    ]

    operations = [
        migrations.AlterField(
            model_name='order',
            name='status',
            field=models.CharField(choices=[('P', 'Pending'), ('D', 'Delivered')], default='P', max_length=1),
        ),
    ]
