services:
  redis:
    image: redis:alpine
    ports:
      - "6379:6379"
    networks:
      - web-network

  web:
    build: .
    command: gunicorn --bind 0.0.0.0:8000 eCommercePlatform.wsgi:application
    volumes:
      - .:/app
    ports:
      - "8000:8000"
    env_file:
      - .env
    depends_on:
      - celery
      - celery-beat
      - redis
    networks:
      - web-network

  celery:
    build: .
    command: celery -A eCommercePlatform worker --loglevel=info
    volumes:
      - .:/app
    env_file:
      - .env
    depends_on:
      - redis
    networks:
      - web-network

  celery-beat:
    build: .
    command: celery -A eCommercePlatform beat --loglevel=info
    volumes:
      - .:/app
    env_file:
      - .env
    depends_on:
      - celery
      - redis
    networks:
      - web-network

volumes:
  static-data:
  web-data:
  redis-data:

networks:
  web-network:
    driver: bridge
